# Generated by Django 4.0 on 2022-01-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpost',
            options={'verbose_name': 'Projet'},
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='image',
            field=models.ImageField(upload_to='portfolio'),
        ),
    ]
