# Generated by Django 4.0 on 2022-01-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectpost_options_alter_projectpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
