# Generated by Django 4.0 on 2022-01-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_categorypost_projectpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.categorypost'),
        ),
    ]
