# Generated by Django 4.0 on 2022-01-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpost',
            name='category',
        ),
    ]
