# Generated by Django 4.0 on 2022-01-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypost',
            options={'verbose_name': 'Catégorie'},
        ),
    ]
